[phases.setup]
nixPkgs = ["conda"]

[phases.install]
cmds = [
  "conda env create -f environment.yml"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "conda activate quantflow-risk-engine && gunicorn --bind 0.0.0.0:$PORT app:app"

