[phases.setup]
nixPkgs = ["wget", "bzip2"]

[phases.install]
cmds = [
  "wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh",
  "bash miniconda.sh -b -p /opt/conda",
  "export PATH=/opt/conda/bin:$PATH",
  "conda env create -f environment.yml"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "export PATH=/opt/conda/bin:$PATH && conda activate quantflow-risk-engine && gunicorn --bind 0.0.0.0:$PORT app:app"

