version: '3.8'

services:
  # Backend API Service (Development)
  backend:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: quantflow-backend-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
      - PORT=5000
    env_file:
      - .env
    volumes:
      - ./backend-api:/app
      - /app/__pycache__
    networks:
      - quantflow-network
    restart: unless-stopped
    command: ["python", "app.py"]

  # Frontend React App (Development)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: quantflow-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_API_URL=http://localhost:5000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - quantflow-network
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  quantflow-network:
    driver: bridge
