version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    container_name: quantflow-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - PORT=5000
    env_file:
      - .env
    volumes:
      - ./backend-api:/app
      - /app/__pycache__
    networks:
      - quantflow-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quantflow-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_API_URL=http://localhost:5000
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - quantflow-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  quantflow-network:
    driver: bridge

volumes:
  backend_cache:
    driver: local
